# Generated by Django 5.2.2 on 2025-07-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0001_initial'),
        ('main', '0007_alter_category_name_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                    to='main.product'),
        ),
    ]
