# Generated by Django 5.2.2 on 2025-06-09 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.IntegerField(blank=True, default=0, help_text='Процент скидки от 1-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='status_discount',
            field=models.BooleanField(default=False),
        ),
    ]
