# Generated by Django 5.2.2 on 2025-06-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_percent_product_status_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'status_discount')},
        ),
    ]
