# Generated by Django 5.2.2 on 2025-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Исходная цена до скидки (заполняется автоматически при наличии скидки)', max_digits=10, null=True),
        ),
    ]
