# Generated by Django 5.2.2 on 2025-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clothingsize_shoessize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingsize',
            options={'ordering': ('name',), 'verbose_name_plural': 'Clothing Sizes'},
        ),
        migrations.AlterModelOptions(
            name='shoessize',
            options={'ordering': ('name',), 'verbose_name_plural': 'Shoes Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_sizes',
            field=models.ManyToManyField(blank=True, to='main.clothingsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='shoes_sizes',
            field=models.ManyToManyField(blank=True, to='main.shoessize'),
        ),
    ]
