# Generated by Django 5.2.2 on 2025-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_alter_clothingsize_options_alter_shoessize_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
