# Generated by Django 5.2.2 on 2025-07-31 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_size_remove_product_clothing_sizes_and_more'),
        ('orders', '0005_alter_orderitem_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothingSize',
        ),
        migrations.DeleteModel(
            name='ShoesSize',
        ),
    ]
