# Generated by Django 5.2.2 on 2025-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_alter_order_payment_provider_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'),
                                            ('canceled', 'Canceled')], default='pending', max_length=20, null=True),
        ),
    ]
