# Generated by Django 5.2.2 on 2025-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_remove_order_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
