# Generated by Django 5.2.2 on 2025-07-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_size_remove_product_clothing_sizes_and_more'),
        ('orders', '0004_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size'),
        ),
    ]
